# Generated by Django 5.0.6 on 2024-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
            ],
        ),
    ]
