# Generated by Django 5.0.6 on 2024-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
